name: deploy-to-netlify
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install packages
        run: yarn install
      - name: build
        run: yarn build
      - name: deploy to netlify
        run: >
          npx netlify deploy
          --prod
          --dir=build
          --message="${{ github.event.commits[0].message }}"
          --site=${{ secrets.NETLIFY_APP }}
          --auth=${{ secrets.NETLIFY_TOKEN }}
